version: '3'

services:
  web:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend/data:/app/data
    restart: always
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
